const DEFAULT_CHART_BACKGROUND_COLOR = '#f3f3f3';
const DEFAULT_CHART_WIDTH = 600;
const DEFAULT_CHART_HEIGHT = 400;
const DEFAULT_AXES_SEGMENTS = 5;
const DEFAULT_CANVAS_SPACING = 30;

export {
  DEFAULT_CHART_BACKGROUND_COLOR,
  DEFAULT_AXES_SEGMENTS,
  DEFAULT_CHART_WIDTH,
  DEFAULT_CHART_HEIGHT,
  DEFAULT_CANVAS_SPACING,
};
